/*
Convex App - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestLoadLoadOne type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestLoadLoadOne{}

// RequestLoadLoadOne struct for RequestLoadLoadOne
type RequestLoadLoadOne struct {
	Args RequestLoadLoadOneArgs `json:"args"`
}

type _RequestLoadLoadOne RequestLoadLoadOne

// NewRequestLoadLoadOne instantiates a new RequestLoadLoadOne object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestLoadLoadOne(args RequestLoadLoadOneArgs) *RequestLoadLoadOne {
	this := RequestLoadLoadOne{}
	this.Args = args
	return &this
}

// NewRequestLoadLoadOneWithDefaults instantiates a new RequestLoadLoadOne object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestLoadLoadOneWithDefaults() *RequestLoadLoadOne {
	this := RequestLoadLoadOne{}
	return &this
}

// GetArgs returns the Args field value
func (o *RequestLoadLoadOne) GetArgs() RequestLoadLoadOneArgs {
	if o == nil {
		var ret RequestLoadLoadOneArgs
		return ret
	}

	return o.Args
}

// GetArgsOk returns a tuple with the Args field value
// and a boolean to check if the value has been set.
func (o *RequestLoadLoadOne) GetArgsOk() (*RequestLoadLoadOneArgs, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Args, true
}

// SetArgs sets field value
func (o *RequestLoadLoadOne) SetArgs(v RequestLoadLoadOneArgs) {
	o.Args = v
}

func (o RequestLoadLoadOne) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestLoadLoadOne) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["args"] = o.Args
	return toSerialize, nil
}

func (o *RequestLoadLoadOne) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"args",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestLoadLoadOne := _RequestLoadLoadOne{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestLoadLoadOne)

	if err != nil {
		return err
	}

	*o = RequestLoadLoadOne(varRequestLoadLoadOne)

	return err
}

type NullableRequestLoadLoadOne struct {
	value *RequestLoadLoadOne
	isSet bool
}

func (v NullableRequestLoadLoadOne) Get() *RequestLoadLoadOne {
	return v.value
}

func (v *NullableRequestLoadLoadOne) Set(val *RequestLoadLoadOne) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestLoadLoadOne) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestLoadLoadOne) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestLoadLoadOne(val *RequestLoadLoadOne) *NullableRequestLoadLoadOne {
	return &NullableRequestLoadLoadOne{value: val, isSet: true}
}

func (v NullableRequestLoadLoadOne) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestLoadLoadOne) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


