/*
Convex App - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ResponseTestTMutationValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseTestTMutationValue{}

// ResponseTestTMutationValue struct for ResponseTestTMutationValue
type ResponseTestTMutationValue struct {
	Value *string `json:"value,omitempty"`
}

// NewResponseTestTMutationValue instantiates a new ResponseTestTMutationValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseTestTMutationValue() *ResponseTestTMutationValue {
	this := ResponseTestTMutationValue{}
	return &this
}

// NewResponseTestTMutationValueWithDefaults instantiates a new ResponseTestTMutationValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseTestTMutationValueWithDefaults() *ResponseTestTMutationValue {
	this := ResponseTestTMutationValue{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *ResponseTestTMutationValue) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponseTestTMutationValue) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *ResponseTestTMutationValue) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *ResponseTestTMutationValue) SetValue(v string) {
	o.Value = &v
}

func (o ResponseTestTMutationValue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseTestTMutationValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableResponseTestTMutationValue struct {
	value *ResponseTestTMutationValue
	isSet bool
}

func (v NullableResponseTestTMutationValue) Get() *ResponseTestTMutationValue {
	return v.value
}

func (v *NullableResponseTestTMutationValue) Set(val *ResponseTestTMutationValue) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseTestTMutationValue) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseTestTMutationValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseTestTMutationValue(val *ResponseTestTMutationValue) *NullableResponseTestTMutationValue {
	return &NullableResponseTestTMutationValue{value: val, isSet: true}
}

func (v NullableResponseTestTMutationValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseTestTMutationValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


