/*
Convex App - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestLoadLoadAll type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestLoadLoadAll{}

// RequestLoadLoadAll struct for RequestLoadLoadAll
type RequestLoadLoadAll struct {
	Args RequestClearDefaultArgs `json:"args"`
}

type _RequestLoadLoadAll RequestLoadLoadAll

// NewRequestLoadLoadAll instantiates a new RequestLoadLoadAll object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestLoadLoadAll(args RequestClearDefaultArgs) *RequestLoadLoadAll {
	this := RequestLoadLoadAll{}
	this.Args = args
	return &this
}

// NewRequestLoadLoadAllWithDefaults instantiates a new RequestLoadLoadAll object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestLoadLoadAllWithDefaults() *RequestLoadLoadAll {
	this := RequestLoadLoadAll{}
	return &this
}

// GetArgs returns the Args field value
func (o *RequestLoadLoadAll) GetArgs() RequestClearDefaultArgs {
	if o == nil {
		var ret RequestClearDefaultArgs
		return ret
	}

	return o.Args
}

// GetArgsOk returns a tuple with the Args field value
// and a boolean to check if the value has been set.
func (o *RequestLoadLoadAll) GetArgsOk() (*RequestClearDefaultArgs, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Args, true
}

// SetArgs sets field value
func (o *RequestLoadLoadAll) SetArgs(v RequestClearDefaultArgs) {
	o.Args = v
}

func (o RequestLoadLoadAll) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestLoadLoadAll) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["args"] = o.Args
	return toSerialize, nil
}

func (o *RequestLoadLoadAll) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"args",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestLoadLoadAll := _RequestLoadLoadAll{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestLoadLoadAll)

	if err != nil {
		return err
	}

	*o = RequestLoadLoadAll(varRequestLoadLoadAll)

	return err
}

type NullableRequestLoadLoadAll struct {
	value *RequestLoadLoadAll
	isSet bool
}

func (v NullableRequestLoadLoadAll) Get() *RequestLoadLoadAll {
	return v.value
}

func (v *NullableRequestLoadLoadAll) Set(val *RequestLoadLoadAll) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestLoadLoadAll) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestLoadLoadAll) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestLoadLoadAll(val *RequestLoadLoadAll) *NullableRequestLoadLoadAll {
	return &NullableRequestLoadLoadAll{value: val, isSet: true}
}

func (v NullableRequestLoadLoadAll) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestLoadLoadAll) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


