/*
Convex App - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestClearDeleteOneArgs type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestClearDeleteOneArgs{}

// RequestClearDeleteOneArgs struct for RequestClearDeleteOneArgs
type RequestClearDeleteOneArgs struct {
	NormalizedId string `json:"normalizedId"`
	Token string `json:"token"`
}

type _RequestClearDeleteOneArgs RequestClearDeleteOneArgs

// NewRequestClearDeleteOneArgs instantiates a new RequestClearDeleteOneArgs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestClearDeleteOneArgs(normalizedId string, token string) *RequestClearDeleteOneArgs {
	this := RequestClearDeleteOneArgs{}
	this.NormalizedId = normalizedId
	this.Token = token
	return &this
}

// NewRequestClearDeleteOneArgsWithDefaults instantiates a new RequestClearDeleteOneArgs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestClearDeleteOneArgsWithDefaults() *RequestClearDeleteOneArgs {
	this := RequestClearDeleteOneArgs{}
	return &this
}

// GetNormalizedId returns the NormalizedId field value
func (o *RequestClearDeleteOneArgs) GetNormalizedId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NormalizedId
}

// GetNormalizedIdOk returns a tuple with the NormalizedId field value
// and a boolean to check if the value has been set.
func (o *RequestClearDeleteOneArgs) GetNormalizedIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NormalizedId, true
}

// SetNormalizedId sets field value
func (o *RequestClearDeleteOneArgs) SetNormalizedId(v string) {
	o.NormalizedId = v
}

// GetToken returns the Token field value
func (o *RequestClearDeleteOneArgs) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *RequestClearDeleteOneArgs) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *RequestClearDeleteOneArgs) SetToken(v string) {
	o.Token = v
}

func (o RequestClearDeleteOneArgs) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestClearDeleteOneArgs) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["normalizedId"] = o.NormalizedId
	toSerialize["token"] = o.Token
	return toSerialize, nil
}

func (o *RequestClearDeleteOneArgs) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"normalizedId",
		"token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestClearDeleteOneArgs := _RequestClearDeleteOneArgs{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestClearDeleteOneArgs)

	if err != nil {
		return err
	}

	*o = RequestClearDeleteOneArgs(varRequestClearDeleteOneArgs)

	return err
}

type NullableRequestClearDeleteOneArgs struct {
	value *RequestClearDeleteOneArgs
	isSet bool
}

func (v NullableRequestClearDeleteOneArgs) Get() *RequestClearDeleteOneArgs {
	return v.value
}

func (v *NullableRequestClearDeleteOneArgs) Set(val *RequestClearDeleteOneArgs) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestClearDeleteOneArgs) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestClearDeleteOneArgs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestClearDeleteOneArgs(val *RequestClearDeleteOneArgs) *NullableRequestClearDeleteOneArgs {
	return &NullableRequestClearDeleteOneArgs{value: val, isSet: true}
}

func (v NullableRequestClearDeleteOneArgs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestClearDeleteOneArgs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


