/*
Convex App - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestClearDefaultArgs type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestClearDefaultArgs{}

// RequestClearDefaultArgs struct for RequestClearDefaultArgs
type RequestClearDefaultArgs struct {
	Token string `json:"token"`
}

type _RequestClearDefaultArgs RequestClearDefaultArgs

// NewRequestClearDefaultArgs instantiates a new RequestClearDefaultArgs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestClearDefaultArgs(token string) *RequestClearDefaultArgs {
	this := RequestClearDefaultArgs{}
	this.Token = token
	return &this
}

// NewRequestClearDefaultArgsWithDefaults instantiates a new RequestClearDefaultArgs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestClearDefaultArgsWithDefaults() *RequestClearDefaultArgs {
	this := RequestClearDefaultArgs{}
	return &this
}

// GetToken returns the Token field value
func (o *RequestClearDefaultArgs) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *RequestClearDefaultArgs) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *RequestClearDefaultArgs) SetToken(v string) {
	o.Token = v
}

func (o RequestClearDefaultArgs) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestClearDefaultArgs) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["token"] = o.Token
	return toSerialize, nil
}

func (o *RequestClearDefaultArgs) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestClearDefaultArgs := _RequestClearDefaultArgs{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestClearDefaultArgs)

	if err != nil {
		return err
	}

	*o = RequestClearDefaultArgs(varRequestClearDefaultArgs)

	return err
}

type NullableRequestClearDefaultArgs struct {
	value *RequestClearDefaultArgs
	isSet bool
}

func (v NullableRequestClearDefaultArgs) Get() *RequestClearDefaultArgs {
	return v.value
}

func (v *NullableRequestClearDefaultArgs) Set(val *RequestClearDefaultArgs) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestClearDefaultArgs) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestClearDefaultArgs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestClearDefaultArgs(val *RequestClearDefaultArgs) *NullableRequestClearDefaultArgs {
	return &NullableRequestClearDefaultArgs{value: val, isSet: true}
}

func (v NullableRequestClearDefaultArgs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestClearDefaultArgs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


