/*
Convex App - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestClearDeleteOne type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestClearDeleteOne{}

// RequestClearDeleteOne struct for RequestClearDeleteOne
type RequestClearDeleteOne struct {
	Args RequestClearDeleteOneArgs `json:"args"`
}

type _RequestClearDeleteOne RequestClearDeleteOne

// NewRequestClearDeleteOne instantiates a new RequestClearDeleteOne object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestClearDeleteOne(args RequestClearDeleteOneArgs) *RequestClearDeleteOne {
	this := RequestClearDeleteOne{}
	this.Args = args
	return &this
}

// NewRequestClearDeleteOneWithDefaults instantiates a new RequestClearDeleteOne object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestClearDeleteOneWithDefaults() *RequestClearDeleteOne {
	this := RequestClearDeleteOne{}
	return &this
}

// GetArgs returns the Args field value
func (o *RequestClearDeleteOne) GetArgs() RequestClearDeleteOneArgs {
	if o == nil {
		var ret RequestClearDeleteOneArgs
		return ret
	}

	return o.Args
}

// GetArgsOk returns a tuple with the Args field value
// and a boolean to check if the value has been set.
func (o *RequestClearDeleteOne) GetArgsOk() (*RequestClearDeleteOneArgs, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Args, true
}

// SetArgs sets field value
func (o *RequestClearDeleteOne) SetArgs(v RequestClearDeleteOneArgs) {
	o.Args = v
}

func (o RequestClearDeleteOne) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestClearDeleteOne) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["args"] = o.Args
	return toSerialize, nil
}

func (o *RequestClearDeleteOne) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"args",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestClearDeleteOne := _RequestClearDeleteOne{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestClearDeleteOne)

	if err != nil {
		return err
	}

	*o = RequestClearDeleteOne(varRequestClearDeleteOne)

	return err
}

type NullableRequestClearDeleteOne struct {
	value *RequestClearDeleteOne
	isSet bool
}

func (v NullableRequestClearDeleteOne) Get() *RequestClearDeleteOne {
	return v.value
}

func (v *NullableRequestClearDeleteOne) Set(val *RequestClearDeleteOne) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestClearDeleteOne) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestClearDeleteOne) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestClearDeleteOne(val *RequestClearDeleteOne) *NullableRequestClearDeleteOne {
	return &NullableRequestClearDeleteOne{value: val, isSet: true}
}

func (v NullableRequestClearDeleteOne) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestClearDeleteOne) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


