/*
Convex App - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestStoreDefault type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestStoreDefault{}

// RequestStoreDefault struct for RequestStoreDefault
type RequestStoreDefault struct {
	Args RequestStoreDefaultArgs `json:"args"`
}

type _RequestStoreDefault RequestStoreDefault

// NewRequestStoreDefault instantiates a new RequestStoreDefault object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestStoreDefault(args RequestStoreDefaultArgs) *RequestStoreDefault {
	this := RequestStoreDefault{}
	this.Args = args
	return &this
}

// NewRequestStoreDefaultWithDefaults instantiates a new RequestStoreDefault object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestStoreDefaultWithDefaults() *RequestStoreDefault {
	this := RequestStoreDefault{}
	return &this
}

// GetArgs returns the Args field value
func (o *RequestStoreDefault) GetArgs() RequestStoreDefaultArgs {
	if o == nil {
		var ret RequestStoreDefaultArgs
		return ret
	}

	return o.Args
}

// GetArgsOk returns a tuple with the Args field value
// and a boolean to check if the value has been set.
func (o *RequestStoreDefault) GetArgsOk() (*RequestStoreDefaultArgs, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Args, true
}

// SetArgs sets field value
func (o *RequestStoreDefault) SetArgs(v RequestStoreDefaultArgs) {
	o.Args = v
}

func (o RequestStoreDefault) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestStoreDefault) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["args"] = o.Args
	return toSerialize, nil
}

func (o *RequestStoreDefault) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"args",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestStoreDefault := _RequestStoreDefault{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestStoreDefault)

	if err != nil {
		return err
	}

	*o = RequestStoreDefault(varRequestStoreDefault)

	return err
}

type NullableRequestStoreDefault struct {
	value *RequestStoreDefault
	isSet bool
}

func (v NullableRequestStoreDefault) Get() *RequestStoreDefault {
	return v.value
}

func (v *NullableRequestStoreDefault) Set(val *RequestStoreDefault) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestStoreDefault) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestStoreDefault) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestStoreDefault(val *RequestStoreDefault) *NullableRequestStoreDefault {
	return &NullableRequestStoreDefault{value: val, isSet: true}
}

func (v NullableRequestStoreDefault) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestStoreDefault) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


