/*
Convex App - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RequestStatsSaveStatsArgs type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestStatsSaveStatsArgs{}

// RequestStatsSaveStatsArgs struct for RequestStatsSaveStatsArgs
type RequestStatsSaveStatsArgs struct {
	Stats map[string]interface{} `json:"stats"`
	Token string `json:"token"`
}

type _RequestStatsSaveStatsArgs RequestStatsSaveStatsArgs

// NewRequestStatsSaveStatsArgs instantiates a new RequestStatsSaveStatsArgs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestStatsSaveStatsArgs(stats map[string]interface{}, token string) *RequestStatsSaveStatsArgs {
	this := RequestStatsSaveStatsArgs{}
	this.Stats = stats
	this.Token = token
	return &this
}

// NewRequestStatsSaveStatsArgsWithDefaults instantiates a new RequestStatsSaveStatsArgs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestStatsSaveStatsArgsWithDefaults() *RequestStatsSaveStatsArgs {
	this := RequestStatsSaveStatsArgs{}
	return &this
}

// GetStats returns the Stats field value
func (o *RequestStatsSaveStatsArgs) GetStats() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Stats
}

// GetStatsOk returns a tuple with the Stats field value
// and a boolean to check if the value has been set.
func (o *RequestStatsSaveStatsArgs) GetStatsOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Stats, true
}

// SetStats sets field value
func (o *RequestStatsSaveStatsArgs) SetStats(v map[string]interface{}) {
	o.Stats = v
}

// GetToken returns the Token field value
func (o *RequestStatsSaveStatsArgs) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *RequestStatsSaveStatsArgs) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *RequestStatsSaveStatsArgs) SetToken(v string) {
	o.Token = v
}

func (o RequestStatsSaveStatsArgs) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestStatsSaveStatsArgs) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["stats"] = o.Stats
	toSerialize["token"] = o.Token
	return toSerialize, nil
}

func (o *RequestStatsSaveStatsArgs) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"stats",
		"token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestStatsSaveStatsArgs := _RequestStatsSaveStatsArgs{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRequestStatsSaveStatsArgs)

	if err != nil {
		return err
	}

	*o = RequestStatsSaveStatsArgs(varRequestStatsSaveStatsArgs)

	return err
}

type NullableRequestStatsSaveStatsArgs struct {
	value *RequestStatsSaveStatsArgs
	isSet bool
}

func (v NullableRequestStatsSaveStatsArgs) Get() *RequestStatsSaveStatsArgs {
	return v.value
}

func (v *NullableRequestStatsSaveStatsArgs) Set(val *RequestStatsSaveStatsArgs) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestStatsSaveStatsArgs) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestStatsSaveStatsArgs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestStatsSaveStatsArgs(val *RequestStatsSaveStatsArgs) *NullableRequestStatsSaveStatsArgs {
	return &NullableRequestStatsSaveStatsArgs{value: val, isSet: true}
}

func (v NullableRequestStatsSaveStatsArgs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestStatsSaveStatsArgs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


